Algoritmo "Variaveis"
// Disciplina  : Algoritmos e Lógica I
// Professor   : Cleison Melo
// Descrição   : Utilização de variaveis
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/05/2020
Var
// Seção de Declarações das variáveis 
//primeiro nome
//segundo nome
//idade
//cidade
//endereço

          primeiroNome, segundoNome: caractere
          idade: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo